# -*- coding: utf-8 -*-
"""ParalelismoRecursivo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MB_fZDz0JcXEoqrQUCPUUBCLt_6l4S5M
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

dataset = pd.read_csv('Teste.csv', sep = ";")
dataset2 = pd.read_csv('Teste2.csv', sep = ";")

dataset.columns = ['ID', 'TamanhoArray', 'TempoCriacao', 'TempoSort', 'Processadores']
dataset2.columns = ['ID', 'TamanhoArray', 'TempoCriacao', 'TempoSort', 'Processadores']

dataset.head

dataset['TempoExecucao'] = pd.Series(dataset['TempoCriacao']+dataset['TempoSort'], index=dataset.index)
dataset2['TempoExecucao'] = pd.Series(dataset2['TempoCriacao']+dataset2['TempoSort'], index=dataset2.index)

is4 = dataset['Processadores'] == 4
Processadores4 = dataset[is4]
is1 = dataset['Processadores'] == 1
Processadores1 = dataset[is1]

plt.scatter( Processadores4['TamanhoArray'], Processadores4['TempoExecucao'],)

plt.title('Desempenho')
z = np.polyfit(Processadores4['TamanhoArray'], Processadores4['TempoExecucao'], 1)
p = np.poly1d(z)
plt.plot(Processadores4['TamanhoArray'],p(Processadores4['TamanhoArray']),"r--", label="Paralelo")
plt.scatter(Processadores1['TamanhoArray'], Processadores1['TempoExecucao'] )
z2 = np.polyfit(Processadores1['TamanhoArray'], Processadores1['TempoExecucao'], 1)
p2 = np.poly1d(z2)
plt.plot(Processadores1['TamanhoArray'],p2(Processadores1['TamanhoArray']),"r--", color= 'green',  label = "Sequencial")
plt.legend()
plt.show()

dataset2['Speedup'] = pd.Series(1/(1-(dataset2['TempoSort']/dataset2['TempoExecucao'])+(dataset2['TempoSort']/dataset2['TempoExecucao'])/dataset2['Processadores']), index=dataset2.index)

dataset2['Eficiencia'] = pd.Series(dataset2['Speedup']/dataset2['Processadores'], index=dataset2.index)

plt.scatter(dataset2['Processadores'], dataset2['Speedup'])
plt.tight_layout()
plt.title('Processadores x Speedup')
z = np.polyfit(dataset2['Processadores'], dataset2['Speedup'], 4)
p = np.poly1d(z)
plt.plot(dataset2['Processadores'],p(dataset2['Processadores']),"r--")
plt.show()

plt.scatter(dataset2['Processadores'], dataset2['Eficiencia'])
plt.tight_layout()
z = np.polyfit(dataset2['Processadores'], dataset2['Eficiencia'], 4)
p = np.poly1d(z)
plt.plot(dataset2['Processadores'],p(dataset2['Processadores']),"r--")
plt.title('Processadores x Eficiencia')
plt.show()

